# === Nodes involved in the cluster definition  ========================================================================
all:
  children:
    central:
      hosts:
        node-00:
          ansible_host: 10.1.10.1
          hostname: node-00.intel.r7g.org
    cluster:
      children:
        controllers:
          hosts:
            node-01:
              ansible_host: 10.1.10.11
              hostname: node-01.intel.r7g.org
              node_id: 1
            node-02:
              ansible_host: 10.1.10.12
              hostname: node-02.intel.r7g.org
              node_id: 2
            node-03:
              ansible_host: 10.1.10.13
              hostname: node-03.intel.r7g.org
              node_id: 3
        brokers:
          hosts:
            node-04:
              ansible_host: 10.1.10.21
              hostname: node-04.intel.r7g.org
              node_id: 4
            node-05:
              ansible_host: 10.1.10.22
              hostname: node-05.intel.r7g.org
              node_id: 5
            node-06:
              ansible_host: 10.1.10.23
              hostname: node-06.intel.r7g.org
              node_id: 6
        connect:
          hosts:
            node-07:
              ansible_host: 10.1.10.31
              hostname: node-07.intel.r7g.org
              node_id: 7
            node-08:
              ansible_host: 10.1.10.32
              hostname: node-08.intel.r7g.org
              node_id: 8
            node-09:
              ansible_host: 10.1.10.33
              hostname: node-09.intel.r7g.org
              node_id: 9
        schema:
          hosts:
            node-10:
              ansible_host: 10.1.10.41
              hostname: node-10.intel.r7g.org
              node_id: 10
            node-11:
              ansible_host: 10.1.10.42
              hostname: node-11.intel.r7g.org
              node_id: 11
            node-12:
              ansible_host: 10.1.10.43
              hostname: node-12.intel.r7g.org
              node_id: 12
        ksql:
          hosts:
            node-13:
              ansible_host: 10.1.10.51
              hostname: node-13.intel.r7g.org
              node_id: 13
            node-14:
              ansible_host: 10.1.10.52
              hostname: node-14.intel.r7g.org
              node_id: 14
            node-15:
              ansible_host: 10.1.10.53
              hostname: node-15.intel.r7g.org
              node_id: 15
