# === Credentials parameters ===========================================================================================

# true - to generate the credentials file and ability to run ACL commands
# false - to create guest enabled cluster - everybody can do anything
use_credentials: true

# Directory on central for credentials generation.
storage_credentials_path: "/data/cluster/credentials"

# this is the only source of truth for the deployments
# * credentials file is generated according to this list
# * ACL permission opt-in run over that nested structure
# * admin is admin, no other admin
credentials:
  - username: "admin"
    password: "insecure"
    permissions:
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: "All"
      - resource_type: "topic"
        resource_name: "*"
        operation: "All"
      - resource_type: "group"
        resource_name: "*"
        operation: "All"
      - resource_type: "transactional-id"
        resource_name: "*"
        operation: "All"
      - resource_type: "delegation-token"
        resource_name: "*"
        operation: "All"

  - username: "schema"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "_schemas"
        operation: "All"
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["Create", "Describe"]
      - resource_type: "group"
        resource_name: "cluster-schema"
        operation: [ "Read", "Describe" ]

  - username: "connector"
    password: "insecure"
    permissions:
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["Create", "Describe", "AlterConfigs", "IdempotentWrite"]

      - resource_type: "topic"
        resource_name: "cluster-connect-configs"
        operation: ["Create", "Describe", "Write", "Read", "Delete", "Alter"]

      - resource_type: "topic"
        resource_name: "cluster-connect-offsets"
        operation: ["Create", "Describe", "Write", "Read", "Delete", "Alter"]

      - resource_type: "topic"
        resource_name: "cluster-connect-status"
        operation: ["Create", "Describe", "Write", "Read", "Delete", "Alter"]

      - resource_type: "topic"
        resource_name: "_schemas"
        operation: ["Create", "Describe", "Write", "Read"]

      - resource_type: "topic"
        resource_name: "*"
        operation: ["Describe", "Write", "Read", "Alter"]

      - resource_type: "group"
        resource_name: "cluster-connect"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-mysql-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-db2-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-mssql-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-mongodb-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-postgresql-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-oracledb-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "transactional-id"
        resource_name: "*"
        operation: ["All"]

  - username: "ksql"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "_schemas"
        operation: "All"
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["Create", "Describe"]
      - resource_type: "group"
        resource_name: "cluster-schema"
        operation: [ "Read", "Describe" ]

  - username: "pub"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: [ "Write", "Read" ]

  - username: "sub"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: "Read"

  - username: "node-07.intel.r7g.org"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: "All"
      - resource_type: "cluster"
        resource_name: "*"
        operation: ["All"]
      - resource_type: "group"
        resource_name: "*"
        operation: [ "All" ]

  - username: "node-08.intel.r7g.org"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: "All"
      - resource_type: "cluster"
        resource_name: "*"
        operation: ["All"]
      - resource_type: "group"
        resource_name: "*"
        operation: [ "All" ]

  - username: "node-09.intel.r7g.org"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: "All"
      - resource_type: "cluster"
        resource_name: "*"
        operation: ["All"]
      - resource_type: "group"
        resource_name: "*"
        operation: [ "All" ]

  - username: "node-10.intel.r7g.org"
    password: "insecure"
    permissions:
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["Create", "Describe", "AlterConfigs", "IdempotentWrite"]

      - resource_type: "topic"
        resource_name: "cluster-connect-configs"
        operation: ["Create", "Describe", "Write", "Read", "Delete", "Alter"]

      - resource_type: "topic"
        resource_name: "cluster-connect-offsets"
        operation: ["Create", "Describe", "Write", "Read", "Delete", "Alter"]

      - resource_type: "topic"
        resource_name: "cluster-connect-status"
        operation: ["Create", "Describe", "Write", "Read", "Delete", "Alter"]

      - resource_type: "topic"
        resource_name: "_schemas"
        operation: ["Create", "Describe", "Write", "Read"]

      - resource_type: "topic"
        resource_name: "*"
        operation: ["All"]

      - resource_type: "group"
        resource_name: "cluster-connect"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-mysql-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-db2-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-mssql-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-mongodb-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-postgresql-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-oracledb-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "transactional-id"
        resource_name: "*"
        operation: ["All"]

  - username: "node-11.intel.r7g.org"
    password: "insecure"
    permissions:
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["Create", "Describe", "AlterConfigs", "IdempotentWrite"]

      - resource_type: "topic"
        resource_name: "cluster-connect-configs"
        operation: ["Create", "Describe", "Write", "Read", "Delete", "Alter"]

      - resource_type: "topic"
        resource_name: "cluster-connect-offsets"
        operation: ["Create", "Describe", "Write", "Read", "Delete", "Alter"]

      - resource_type: "topic"
        resource_name: "cluster-connect-status"
        operation: ["Create", "Describe", "Write", "Read", "Delete", "Alter"]

      - resource_type: "topic"
        resource_name: "_schemas"
        operation: ["Create", "Describe", "Write", "Read"]

      - resource_type: "topic"
        resource_name: "*"
        operation: ["All"]

      - resource_type: "group"
        resource_name: "cluster-connect"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-mysql-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-db2-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-mssql-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-mongodb-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-postgresql-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-oracledb-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "transactional-id"
        resource_name: "*"
        operation: ["All"]

  - username: "node-12.intel.r7g.org"
    password: "insecure"
    permissions:
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["Create", "Describe", "AlterConfigs", "IdempotentWrite"]

      - resource_type: "topic"
        resource_name: "cluster-connect-configs"
        operation: ["Create", "Describe", "Write", "Read", "Delete", "Alter"]

      - resource_type: "topic"
        resource_name: "cluster-connect-offsets"
        operation: ["Create", "Describe", "Write", "Read", "Delete", "Alter"]

      - resource_type: "topic"
        resource_name: "cluster-connect-status"
        operation: ["Create", "Describe", "Write", "Read", "Delete", "Alter"]

      - resource_type: "topic"
        resource_name: "_schemas"
        operation: ["Create", "Describe", "Write", "Read"]

      - resource_type: "topic"
        resource_name: "*"
        operation: ["All"]

      - resource_type: "group"
        resource_name: "cluster-connect"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-mysql-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-db2-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-mssql-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-mongodb-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-postgresql-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "group"
        resource_name: "cdc-oracledb-schemahistory"
        operation: ["Describe", "Read"]

      - resource_type: "transactional-id"
        resource_name: "*"
        operation: ["All"]

  - username: "node-13.intel.r7g.org"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: [ "All" ]
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["Create", "Describe"]
      - resource_type: "group"
        resource_name: "*"
        operation: [ "All" ]
      - resource_type: "transactional-id"
        resource_name: "*"
        operation: "All"

  - username: "node-14.intel.r7g.org"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: [ "All" ]
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["Create", "Describe"]
      - resource_type: "group"
        resource_name: "*"
        operation: [ "All" ]
      - resource_type: "transactional-id"
        resource_name: "*"
        operation: "All"

  - username: "node-15.intel.r7g.org"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: [ "All" ]
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["Create", "Describe"]
      - resource_type: "group"
        resource_name: "*"
        operation: [ "All" ]
      - resource_type: "transactional-id"
        resource_name: "*"
        operation: "All"
