# === Credentials parameters ===========================================================================================

# true - to generate the credentials file and ability to run ACL commands
# false - to create guest enabled cluster - everybody can do anything
use_credentials: true

# Directory on central for credentials generation.
storage_credentials_path: "/data/cluster/credentials"

# this is the only source of truth for the deployments
# * credentials file is generated according to this list
# * ACL permission opt-in run over that nested structure
# * admin is admin, no other admin
credentials:
  - username: "admin"
    password: "insecure"
    permissions:
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: "all"
      - resource_type: "topic"
        resource_name: "*"
        operation: "all"
      - resource_type: "group"
        resource_name: "*"
        operation: "all"
      - resource_type: "transactional-id"
        resource_name: "*"
        operation: "all"
      - resource_type: "delegation-token"
        resource_name: "*"
        operation: "all"

  - username: "schema"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "_schemas"
        operation: "all"
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["create","describe"]
      - resource_type: "group"
        resource_name: "schema-cluster"
        operation: [ "read", "describe" ]

  - username: "connect"
    password: "insecure"
    permissions:
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["create", "describe"]
      - resource_type: "topic"
        resource_name: "*"
        operation: "all"
      - resource_type: "group"
        resource_name: "connect-cluster"
        operation: "read"
      - resource_type: "group"
        resource_name: "cdc-mysql-schemahistory"
        operation: "read"
      - resource_type: "group"
        resource_name: "cdc-db2-schemahistory"
        operation: "read"
      - resource_type: "group"
        resource_name: "cdc-mssql-schemahistory"
        operation: "read"
      - resource_type: "group"
        resource_name: "cdc-mongodb-schemahistory"
        operation: "read"
      - resource_type: "group"
        resource_name: "cdc-postgresql-schemahistory"
        operation: "read"
      - resource_type: "group"
        resource_name: "cdc-oracledb-schemahistory"
        operation: "read"

  - username: "ksql"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "_schemas"
        operation: "all"
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["create","describe"]
      - resource_type: "group"
        resource_name: "schema-cluster"
        operation: [ "read", "describe" ]

  - username: "pub"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: [ "write", "read" ]

  - username: "sub"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: "read"

  - username: "node-13.intel.r7g.org"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: [ "all" ]
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["create","describe"]
      - resource_type: "group"
        resource_name: "*"
        operation: [ "all" ]
      - resource_type: "transactional-id"
        resource_name: "*"
        operation: "all"

  - username: "node-14.intel.r7g.org"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: [ "all" ]
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["create","describe"]
      - resource_type: "group"
        resource_name: "*"
        operation: [ "all" ]
      - resource_type: "transactional-id"
        resource_name: "*"
        operation: "all"

  - username: "node-15.intel.r7g.org"
    password: "insecure"
    permissions:
      - resource_type: "topic"
        resource_name: "*"
        operation: [ "all" ]
      - resource_type: "cluster"
        resource_name: "kafka-cluster"
        operation: ["create","describe"]
      - resource_type: "group"
        resource_name: "*"
        operation: [ "all" ]
      - resource_type: "transactional-id"
        resource_name: "*"
        operation: "all"
