---
- name: Ensure Credentials directory exists
  tags:
    - credentials_generate
  ansible.builtin.file:
    path: "{{ node_credentials_path }}"
    state: directory
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: '{{ chmod_credentials }}'

- name: Create Server Credentials file on nodes
  tags:
    - credentials_generate
  ansible.builtin.template:
    src: "{{ inventory_dir }}/templates/credentials.j2"
    dest: "{{ node_credentials_file }}"
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: '0755'

- name: Create Client Credentials file on nodes
  tags:
    - credentials_generate
  ansible.builtin.template:
    src: "{{ inventory_dir }}/templates/client_conf.j2"
    dest: "{{ node_client_conf_file }}"
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: '0755'
