---
- name: Remove credentials storage on node-0
  tags:
    - credentials_generate
  delegate_to: node-0
  run_once: true
  ansible.builtin.file:
    path: "{{ storage_credentials_path }}"
    state: absent

- name: Create credentials storage on node-0
  tags:
    - credentials_generate
  delegate_to: node-0
  run_once: true
  ansible.builtin.file:
    path: "{{ storage_credentials_path }}"
    state: directory
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_credentials }}"

- name: Generate SASL_SSL credentials file for each user
  tags:
    - credentials_generate
  when: use_credentials
  delegate_to: node-0
  run_once: true
  ansible.builtin.template:
    src: "{{ inventory_dir }}/templates/user_credentials_sasl_ssl.j2"
    dest: "{{ storage_credentials_path }}/{{ item.username }}.sasl_ssl.properties"
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_credentials }}"
  loop: "{{ credentials }}"
  loop_control:
    label: "{{ item.username }}"
  changed_when: false

- name: Generate SSL credentials file for each user
  tags:
    - credentials_generate
  when: use_credentials
  delegate_to: node-0
  run_once: true
  ansible.builtin.template:
    src: "{{ inventory_dir }}/templates/user_credentials_ssl.j2"
    dest: "{{ storage_credentials_path }}/{{ item.username }}.ssl.properties"
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_credentials }}"
  loop: "{{ credentials }}"

- name: Create credentials directory on nodes
  tags:
    - credentials_generate
  ansible.builtin.file:
    path: "{{ node_credentials_path }}"
    state: directory
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_credentials }}"

- name: Distribute admin credentials to all nodes
  tags:
    - credentials_generate
  delegate_to: node-0
  with_items:
    - { src: "{{ storage_credentials_path }}/admin.ssl.properties", dest: "{{ node_credentials_path }}/admin.ssl.properties" }
    - { src: "{{ storage_credentials_path }}/admin.sasl_ssl.properties", dest: "{{ node_credentials_path }}/admin.sasl_ssl.properties" }
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: push
    rsync_opts:
      - "--timeout=60"
      - "--checksum"

- name: Distribute connect credentials to connect nodes
  tags:
    - credentials_generate
  delegate_to: node-0
  with_items:
    - { src: "{{ storage_credentials_path }}/connect.ssl.properties", dest: "{{ node_credentials_path }}/connect.ssl.properties" }
    - { src: "{{ storage_credentials_path }}/connect.sasl_ssl.properties", dest: "{{ node_credentials_path }}/connect.sasl_ssl.properties" }
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: push
    rsync_opts:
      - "--timeout=60"
      - "--checksum"
  when: "'connect' in group_names"
