---
- name: Ensure Credentials directory exists
  tags:
    - credentials_generate
  ansible.builtin.file:
    path: "{{ node_credentials_path }}"
    state: directory
    owner: "{{ data_owner_user }}"
    group: "{{ data_owner_group }}"
    mode: '{{ credentials_folder_chmod }}'

- name: Create Credentials file on nodes
  tags:
    - credentials_generate
  ansible.builtin.template:
    src: "{{ inventory_dir }}/templates/*"
    dest: "{{ node_credentials_path }}"
    owner: "{{ data_owner_user }}"
    group: "{{ data_owner_group }}"
    mode: '0755'
