---
- name: Remove existing credentials directory
  tags:
    - credentials_generate
  ansible.builtin.file:
    path: "{{ node_credentials_path }}"
    state: absent

- name: Recreate credentials directory
  tags:
    - credentials_generate
  ansible.builtin.file:
    path: "{{ node_credentials_path }}"
    state: directory
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_credentials }}"

- name: Generate SASL_SSL credentials file for each user
  tags:
    - credentials_generate
  when: use_credentials
  ansible.builtin.template:
    src: "{{ inventory_dir }}/templates/user_credentials_sasl_ssl.j2"
    dest: "{{ node_credentials_path }}/{{ item.username }}.sasl_ssl.properties"
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "0600"
  loop: "{{ credentials }}"

- name: Generate SSL credentials file for each user
  tags:
    - credentials_generate
  when: use_credentials
  ansible.builtin.template:
    src: "{{ inventory_dir }}/templates/user_credentials_ssl.j2"
    dest: "{{ node_credentials_path }}/{{ item.username }}.ssl.properties"
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "0600"
  loop: "{{ credentials }}"
