---
- name: Load kafka_users from an external file
  tags:
    - credentials_generate
  include_vars:
    file: group_vars/all/credentials.yml

- name: Ensure Credentials directory exists
  tags:
    - credentials_generate
  ansible.builtin.file:
    path: "{{ node_credentials_path }}"
    state: directory
    owner: "{{ data_owner_user }}"
    group: "{{ data_owner_group }}"
    mode: '0600'

- name: Create Credentials file on nodes
  tags:
    - credentials_generate
  ansible.builtin.template:
    src: credentials.j2
    dest: "{{ node_credentials_file }}"
    owner: "{{ data_owner_user }}"
    group: "{{ data_owner_group }}"
    mode: '0600'
