---
- name: Fetch first node from the cluster
  tags:
    - credentials_backup
  set_fact:
    first_node: >-
      {{
        (groups['combined'] | default([])) |
        union(groups['brokers'] | default([])) |
        first
      }}

- name: Apply ACLs for each user on the first node of the cluster
  tags:
    - credentials_backup
  delegate_to: "{{ first_node }}"
  with_items: "{{ kafka_users }}"
  with_nested:
    - "{{ item.permissions }}"
  shell: |
    docker exec {{ first_node }} kafka-acls \
      --bootstrap-server localhost:9092 \
      --add --allow-principal User:{{ item.0.username }} \
      --operation {{ item.1.operation }} \
      --{{ item.1.resource_type }} {{ item.1.resource_name }} 
