---
- name: Run credentials generate
  include_tasks: credentials_generate.yml
  tags: credentials_generate

- name: Run credentials apply
  include_tasks: credentials_apply.yml
  tags: credentials_apply

- name: Run credentials backup
  include_tasks: credentials_backup.yml
  tags: credentials_backup

- name: Run credentials restore
  include_tasks: credentials_restore.yml
  tags: credentials_restore

- name: Rotate old credentials backups
  include_tasks: credentials_rotate.yml
  tags: credentials_rotate

