---
- name: Verify archive exists
  tags:
    - config_restore
  delegate_to: kafka-node-0
  run_once: true
  stat:
    path: "{{ restore_archive }}"
  register: archive_stat

- name: Generate KeyStores
  tags: cert_deploy
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', {{ ansible_key_pub }}) }}"
