---
- name: Verify archive exists
  tags:
    - configs_restore
  delegate_to: node-0
  run_once: true
  stat:
    path: "{{ restore_archive }}"
  register: archive_stat

- name: Fail if archive does not exist
  tags:
    - configs_restore
  fail:
    msg: "The specified restore archive {{ restore_archive }} does not exist!"
  when: not archive_stat.stat.exists

- name: Extract configs archive to temp on central
  tags:
    - configs_restore
  delegate_to: node-0
  run_once: true
  unarchive:
    src: "{{ restore_archive }}"
    dest: "{{ storage_temp_path }}"
    remote_src: yes

- name: Push node archives from central into nodes
  tags:
    - configs_restore
  delegate_to: node-0
  synchronize:
    src: "{{ storage_temp_path }}/{{ inventory_hostname }}-configs.tar.zx"
    dest: "{{ node_temp_path }}/{{ inventory_hostname }}-configs.tar.zx"
    mode: push
    rsync_opts:
      - "--timeout=60"
      - "--checksum"

- name: Remove cluster config folder on nodes
  tags:
    - configs_restore
  file:
    path: "{{ node_config_path }}"
    state: absent

- name: Create cluster config folder on nodes
  tags:
    - configs_restore
  file:
    path: "{{ node_config_path }}"
    state: directory
    mode: '0755'

- name: Restore cluster config on nodes
  tags:
    - configs_restore
  unarchive:
    src: "{{ node_temp_path }}/{{ inventory_hostname }}-config.tar.zx"
    dest: "{{ node_config_path }}"
    remote_src: yes
