---
- name: Rotate old config backups
  tags:
    - configs_rotate
  delegate_to: node-0
  run_once: true
  find:
    paths: "{{ storage_cold_path }}/config/rotated/"
    age: "{{ retention_policy_configs }}d"
    recurse: yes
    patterns: "*config.tar.*"
  register: old_configs_backups

- name: Remove old config backups
  tags:
    - configs_rotate
  delegate_to: node-0
  run_once: true
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ old_configs_backups.files }}"

- name: Remove empty directories in data storage
  tags: configs_rotate
  delegate_to: node-0
  run_once: true
  shell: >
    find {{ storage_cold_path }}/config/rotated/ -depth -type d -empty -delete
