ansible_python_interpreter: /usr/bin/python

startup_order:
  - kafka-controller-1
  - kafka-controller-2
  - kafka-controller-3
  - kafka-broker-1
  - kafka-broker-2
  - kafka-broker-3

shutdown_order:
  - kafka-broker-3
  - kafka-broker-2
  - kafka-broker-1
  - kafka-controller-3
  - kafka-controller-2
  - kafka-controller-1

image: confluentinc/cp-kafka:7.8.0
retention_policy: 7
storage_cold: /backup/cold
storage_temp: /data/temp
node_config: /data/cluster/config
node_data: /data/cluster/data
node_temp: /data/temp

# this should be populated as a full path to the archive via cli params
recovery_archive: ""

backup_date: "{{ ansible_date_time.date }}---{{ ansible_date_time.time | replace(':', '-') }}"
backup_config_path: "{{ storage_cold }}/config/rotated/{{ ansible_date_time.year }}/{{ ansible_date_time.month }}/{{ ansible_date_time.day }}"
backup_data_path: "{{ storage_cold }}/data/rotated/{{ ansible_date_time.year }}/{{ ansible_date_time.month }}/{{ ansible_date_time.day }}"
backup_config_archive: "{{ backup_config_path }}/{{ backup_date }}---config.zip"
backup_data_archive: "{{ backup_data_path }}/{{ backup_date }}---data.zip"