---
- name: Deploy SSH public keys on all nodes
  include_tasks: ssh_keys.yml
  tags:
    - ssh_keys

- name: Install prerequisites on all nodes
  include_tasks: prerequisites.yml
  tags:
    - prerequisites

- name: Reboot all nodes
  include_tasks: cluster_reboot.yml
  tags:
    - cluster_reboot

# do not include temp_cleanup here as it is included in playbook level as post/pre steps