---
- name: Deploy SSH public keys on all cluster nodes
  include_tasks: ssh_keys.yml
  tags:
    - ssh_keys

- name: Install prerequisites on all cluster nodes
  include_tasks: prerequisites.yml
  tags:
    - prerequisites

# do not include temp_cleanup here as it is included in playbook level as post/pre steps