# === Nodes involved in the cluster definition  ========================================================================
all:
  children:
    central:
      hosts:
        node-0:
          ansible_host: 10.1.10.1
          hostname: node-0.intel.r7g.org
    cluster:
      children:
        controllers:
          hosts:
            node-1:
              ansible_host: 10.1.11.1
              hostname: node-1.intel.r7g.org
              node_id: 1
            node-2:
              ansible_host: 10.1.11.2
              hostname: node-2.intel.r7g.org
              node_id: 2
            node-3:
              ansible_host: 10.1.11.3
              hostname: node-3.intel.r7g.org
              node_id: 3
        brokers:
          hosts:
            node-4:
              ansible_host: 10.1.12.1
              hostname: node-4.intel.r7g.org
              node_id: 4
            node-5:
              ansible_host: 10.1.12.2
              hostname: node-5.intel.r7g.org
              node_id: 5
            node-6:
              ansible_host: 10.1.12.3
              hostname: node-6.intel.r7g.org
              node_id: 6
        connect:
          hosts:
            node-7:
              ansible_host: 10.1.13.1
              hostname: node-7.intel.r7g.org
              node_id: 7
            node-8:
              ansible_host: 10.1.13.2
              hostname: node-8.intel.r7g.org
              node_id: 8
            node-9:
              ansible_host: 10.1.13.3
              hostname: node-9.intel.r7g.org
              node_id: 9
