---
- name: Ensure Certbot volume directory exists
  tags:
    - certificate_generate
  delegate_to: kafka-node-0
  run_once: true
  ansible.builtin.file:
    path: "{{ certbot_volume_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Cloudflare credentials file
  tags:
    - certificate_generate
  delegate_to: kafka-node-0
  run_once: true
  ansible.builtin.template:
    src: cloudflare.ini.j2
    dest: "{{ certbot_volume_path }}/cloudflare.ini"
    owner: root
    group: root
    mode: '0600'

- name: Run Certbot to renew certificate
  tags:
    - certificate_generate
  delegate_to: kafka-node-0
  run_once: true
  ansible.builtin.shell: >
    docker run --rm -v "{{ certbot_volume_path }}:/etc/letsencrypt"
    -v "{{ certbot_volume_path }}:/var/lib/letsencrypt"
    "{{ docker_certbot_image }}" certonly
    --dns-cloudflare
    --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
    --email "{{ certbot_email }}"
    --agree-tos
    --non-interactive
    {% if certbot_staging %}
    --server https://acme-staging-v02.api.letsencrypt.org/directory
    {% else %}
    --server https://acme-v02.api.letsencrypt.org/directory
    {% endif %}
    --domain "{{ certbot_domain }}"
    {% if force %}
    --force-renewal
    {% endif %}
  args:
    chdir: /tmp
  register: certbot_result

- name: Display Certbot output
  tags:
    - certificate_generate
  delegate_to: kafka-node-0
  run_once: true
  debug:
    var: certbot_result.stdout