- name: Verify certificate files exist on central
  tags:
    - cert_deploy
  delegate_to: node-0
  run_once: true
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ certificate_file_fullchain }}"
    - "{{ certificate_file_key }}"
  register: cert_stats

- name: Fail if any certificate file is missing
  tags:
    - cert_deploy
  delegate_to: node-0
  run_once: true
  fail:
    msg: >
      The specified certificate file {{ item.item }} does not exist!
  when: not item.stat.exists
  with_items: "{{ cert_stats.results }}"

- name: Extract certificate expiration details
  tags:
    - cert_deploy
  delegate_to: node-0
  run_once: true
  shell: |
    cert_date=$(openssl x509 -enddate -noout -in {{ certificate_file_fullchain }} | sed 's/^notAfter=//')
    cert_epoch=$(date -d "$cert_date" +%s)
    current_epoch=$(date +%s)
    cert_days_remaining=$(( (cert_epoch - current_epoch) / 86400 ))
    echo "expiration_date=$cert_date"
    echo "days_remaining=$cert_days_remaining"
  register: cert_details

- name: Parse certificate expiration details
  tags:
    - cert_deploy
  delegate_to: node-0
  run_once: true
  set_fact:
    certificate_expiration_date: "{{ cert_details.stdout_lines | select('search', '^expiration_date=') | map('regex_replace', '^expiration_date=', '') | first }}"
    certificate_expire_in_days: "{{ cert_details.stdout_lines | select('search', '^days_remaining=') | map('regex_replace', '^days_remaining=', '') | first | int }}"

- name: Debug certificate expiration details
  tags:
    - cert_deploy
  delegate_to: node-0
  run_once: true
  debug:
    msg: >
      Raw expiration date: {{ certificate_expiration_date }},
      Days until expiration: {{ certificate_expire_in_days }}.

- name: Fail if certificate is expired or expires soon
  tags:
    - cert_deploy
  delegate_to: node-0
  run_once: true
  fail:
    msg: >
      {% if certificate_expire_in_days | float == 0 %}
      The specified certificate fullchain {{ certificate_file_fullchain }} expires today!
      {% elif certificate_expire_in_days | float < 0 %}
      The specified certificate fullchain {{ certificate_file_fullchain }} expired {{ certificate_expire_in_days | float | abs | round(2) }} days ago!
      {% else %}
      The specified certificate fullchain {{ certificate_file_fullchain }} will expire in {{ certificate_expire_in_days  | float | round(2) }} days!
      {% endif %}
  when: certificate_expire_in_days | float < certificate_expiration_threshold

- name: Generate KeyStore
  tags:
    - cert_deploy
  delegate_to: node-0
  run_once: true
  shell: >
    openssl pkcs12 -export
    -in {{ certificate_file_fullchain }}
    -inkey {{ certificate_file_key }}
    -out {{ certificate_file_p12 }}
    -name {{ keystore_certificate_name }}
    -password pass:keystorepassword
