---
- name: Ensure Certbot volume directory exists
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  ansible.builtin.file:
    path: "{{ storage_certificate_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Cloudflare credentials file
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  ansible.builtin.template:
    src: cloudflare.ini.j2
    dest: "{{ storage_certificate_path }}/cloudflare.ini"
    owner: root
    group: root
    mode: '0600'

- name: Run Certbot to renew certificate
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  ansible.builtin.shell: >
    docker run --rm -v "{{ storage_certificate_path }}:/etc/letsencrypt"
    -v "{{ storage_certificate_path }}:/var/lib/letsencrypt"
    "{{ certbot_docker_image }}" certonly
    --dns-cloudflare
    --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
    --email "{{ certbot_cloudflare_user_email }}"
    --agree-tos
    --non-interactive
    {% if certbot_staging %}
    --server https://acme-staging-v02.api.letsencrypt.org/directory
    {% else %}
    --server https://acme-v02.api.letsencrypt.org/directory
    {% endif %}
    --domain "{{ certbot_subject }}"
    {% if certificate_regenerate_force %}
    --force-renewal
    {% endif %}
  register: certbot_result

- name: Display Certbot output
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  debug:
    var: certbot_result.stdout

- name: Verify certificate files exist on central
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ certificate_file_fullchain }}"
    - "{{ certificate_file_key }}"
  register: cert_stats

- name: Fail if any certificate file is missing
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  fail:
    msg: >
      The specified certificate file {{ item.item }} does not exist!
  when: not item.stat.exists
  with_items: "{{ cert_stats.results }}"

- name: Extract certificate expiration details
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  shell: |
    cert_date=$(openssl x509 -enddate -noout -in {{ certificate_file_fullchain }} | sed 's/^notAfter=//')
    cert_epoch=$(date -d "$cert_date" +%s)
    current_epoch=$(date +%s)
    cert_days_remaining=$(( (cert_epoch - current_epoch) / 86400 ))
    echo "expiration_date=$cert_date"
    echo "days_remaining=$cert_days_remaining"
  register: cert_details

- name: Parse certificate expiration details
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  set_fact:
    certificate_expiration_date: "{{ cert_details.stdout_lines | select('search', '^expiration_date=') | map('regex_replace', '^expiration_date=', '') | first }}"
    certificate_expire_in_days: "{{ cert_details.stdout_lines | select('search', '^days_remaining=') | map('regex_replace', '^days_remaining=', '') | first | int }}"

- name: Debug certificate expiration details
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  debug:
    msg: >
      Raw expiration date: {{ certificate_expiration_date }},
      Days until expiration: {{ certificate_expire_in_days }}.

- name: Fail if certificate is expired or expires soon
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  fail:
    msg: >
      {% if certificate_expire_in_days | float == 0 %}
      The specified certificate fullchain {{ certificate_file_fullchain }} expires today!
      {% elif certificate_expire_in_days | float < 0 %}
      The specified certificate fullchain {{ certificate_file_fullchain }} expired {{ certificate_expire_in_days | float | abs | round(2) }} days ago!
      {% else %}
      The specified certificate fullchain {{ certificate_file_fullchain }} will expire in {{ certificate_expire_in_days  | float | round(2) }} days!
      {% endif %}
  when: certificate_expire_in_days | float < certificate_expiration_threshold

- name: Generate JKS KeyStore from PKCS#12 file
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  shell: >
    openssl pkcs12 -export
    -in {{ certificate_file_fullchain }}
    -inkey {{ certificate_file_key }}
    -out {{ certificate_file_p12 }}
    -name {{ keystore_certificate_name }}
    -password pass:{{ keystore_password }}

- name: Import CA certificate into JKS TrustStore
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  shell: >
    keytool -importkeystore 
      -deststorepass {{ keystore_password }} 
      -destkeypass {{ keystore_password }}
      -destkeystore {{ certificate_file_keystore }} 
      -srckeystore {{ certificate_file_p12 }}
      -srcstoretype PKCS12 
      -srcstorepass {{ keystore_password }} 
      -alias {{ keystore_certificate_name }}

- name: Generate JKS TrustStore
  tags:
    - certificate_generate
  delegate_to: node-0
  run_once: true
  shell: >
    yes | keytool -import 
      -trustcacerts 
      -file {{ certificate_file_fullchain }}
      -alias {{ truststore_ca_name }}
      -keystore {{ certificate_file_truststore }}
      -storepass {{ keystore_password }} 

- name: Verify Keystore file
  tags:
    - certificate_generate
  shell: >
    keytool -list -keystore {{ certificate_file_keystore }}
    -storepass {{ keystore_password }}
  register: keystore_check

- name: Display Keystore Details
  tags:
    - certificate_generate
  debug:
    var: keystore_check.stdout

- name: Verify TrustStore file
  tags:
    - certificate_generate
  shell: >
    keytool -list -keystore {{ certificate_file_truststore }}
    -storepass {{ keystore_password }}
  register: truststore_check

- name: Display TrustStore Details
  tags:
    - certificate_generate
  debug:
    var: truststore_check.stdout

- name: Ensure certificate folder exists on nodes
  tags:
    - certificate_generate
  file:
    path: "{{ node_certificate_path }}"
    state: directory
    mode: '0755'

- name: Push certificate KeyStore from central into nodes
  tags:
    - certificate_generate
  delegate_to: node-0
  synchronize:
    src: "{{ certificate_file_p12 }}"
    dest: "{{ node_certificate_path }}/"
    mode: push

- name: Set ownership and permissions of the certificate folder recursively
  tags:
    - certificate_generate
  ansible.builtin.file:
    path: "{{ node_certificate_path }}"
    owner: "{{ data_owner_user }}"
    group: "{{ data_owner_group }}"
    mode: "0755"
    recurse: true