---
- name: Rotate old credentials backups
  tags:
    - credentials_rotate
  delegate_to: node-0
  run_once: true
  find:
    paths: "{{ storage_cold_path }}/credentials/rotated/"
    age: "{{ retention_policy_credentials }}d"
    recurse: yes
    patterns: "*credentials.tar.*"
  register: old_credentials_backups

- name: Remove old credentials backups
  tags:
    - credentials_rotate
  delegate_to: node-0
  run_once: true
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ old_credentials_backups.files }}"

- name: Remove empty directories in data storage
  tags: credentials_rotate
  delegate_to: node-0
  run_once: true
  shell: >
    find {{ storage_cold_path }}/credentials/rotated/ -depth -type d -empty -delete
