---
- name: Verify archive exists
  tags:
    - credentials_restore
  delegate_to: node-0
  run_once: true
  stat:
    path: "{{ restore_archive }}"
  register: archive_stat

- name: Fail if archive does not exist
  tags:
    - credentials_restore
  fail:
    msg: "The specified restore archive {{ restore_archive }} does not exist!"
  when: not archive_stat.stat.exists

- name: Extract credentials archive to temp on central
  tags:
    - credentials_restore
  delegate_to: node-0
  run_once: true
  unarchive:
    src: "{{ restore_archive }}"
    dest: "{{ storage_temp_path }}"
    remote_src: yes

- name: Create credentials directory on nodes
  tags:
    - credentials_restore
  changed_when: false
  ansible.builtin.file:
    path: "{{ node_credentials_path }}"
    state: directory
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_credentials }}"

- name: Push node archives from node-0 to nodes
  tags:
    - credentials_restore
  delegate_to: node-0
  synchronize:
    src: "{{ storage_temp_path }}/{{ inventory_hostname }}-credentials.tar.xz"
    dest: "{{ node_temp_path }}/{{ inventory_hostname }}-credentials.tar.xz"
    mode: push
    rsync_opts:
      - "--timeout=60"
      - "--checksum"

- name: Restore credentials on nodes
  tags:
    - credentials_restore
  unarchive:
    src: "{{ node_temp_path }}/{{ inventory_hostname }}-credentials.tar.xz"
    dest: "{{ node_credentials_path }}"
    remote_src: yes

- name: Set credentials permissions
  tags:
    - credentials_restore
  delegate_to: node-0
  run_once: true
  ansible.builtin.file:
    path: "{{ node_credentials_path }}"
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_credentials }}"
    recurse: true