---
- name: Create folder for cold rotated backups
  tags:
    - credentials_rotate
  delegate_to: node-00
  run_once: true
  ansible.builtin.file:
    path: "{{ central_credentials_backup_path }}"
    state: directory
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_credentials }}"

- name: Create folder for cold pinned backups
  tags:
    - credentials_rotate
  delegate_to: node-00
  run_once: true
  ansible.builtin.file:
    path: "{{ central_credentials_backup_pinned }}"
    state: directory
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_credentials }}"

- name: Rotate old credentials backups
  tags:
    - credentials_rotate
  delegate_to: node-00
  run_once: true
  find:
    paths: "{{ central_credentials_backup_rotated }}"
    age: "{{ retention_policy_credentials }}d"
    recurse: yes
    patterns: "{{ central_credentials_backup_rotate_pattern }}"
  register: old_credentials_backups

- name: Remove old credentials backups
  tags:
    - credentials_rotate
  delegate_to: node-00
  run_once: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ old_credentials_backups.files }}"

- name: Remove empty credentials directories in cold storage
  tags: credentials_rotate
  delegate_to: node-00
  run_once: true
  shell: >
    find {{ central_credentials_backup_rotated }} -depth -type d -empty -delete
