- name: Cleanup temporary directory on nodes
  tags: backup_config
  file:
    path: "{{ node_temp }}"
    state: absent
  register: node_temp_cleanup_results

- name: Create temporary directory on nodes
  tags: backup_config
  file:
    path: "{{ node_temp }}/{{ inventory_hostname }}"
    state: directory
    mode: '0755'
  register: node_temp_create_results

- name: Cleanup temporary directory on the localhost
  tags: backup_config
  hosts: localhost
  file:
    path: "{{ storage_temp }}"
    state: absent
  register: local_temp_cleanup_results

- name: Create temporary directory on the localhost
  tags: backup_config
  hosts: localhost
  file:
    path: "{{ storage_temp }}"
    state: directory
    mode: '0755'
  register: local_temp_create_results

- name: Copy node configs to temp folder
  tags: backup_config
  shell: cp {{ node_config }}/* {{ node_temp }}/{{ inventory_hostname }}/ -R
  register: copy_config_to_temp_results

- name: Archive Kafka configuration files on nodes
  tags: backup_config
  shell: (cd {{ node_temp }} && tar -czf {{ inventory_hostname }}-config.tar.gz {{ inventory_hostname }})
  register: config_archive_result

- name: Transfer configuration archive to central server
  tags: backup_config
  fetch:
    src: "{{ node_temp }}/{{ inventory_hostname }}-config.tar.gz"
    dest: "{{ storage_temp }}/{{ inventory_hostname }}-config.tar.gz"
    flat: yes
  register: fetch_archive_result

- name: List files in a local directory
  hosts: localhost
  tags: backup_config
  ansible.builtin.find:
    paths: "{{ storage_temp }}"
    file_type: file
  register: local_files

- name: Show list of local files
  tags: backup_config
  run_once: true
  debug:
    var: local_files.files
