---
#- name: Archive cluster configuration files on nodes
#  tags:
#    - backup_config
#  shell: (cd {{ node_config }} && tar -czf {{ node_temp }}/{{ inventory_hostname }}-config.tar.gz ./)
#  register: config_archive_result

- name: Archive cluster configuration files on nodes
  tags:
    - backup_config
  community.general.archive:
    path: "{{ node_config }}"  # The directory or files to be archived
    dest: "{{ node_temp }}/{{ inventory_hostname }}-config.zip"  # Destination archive
    format: zip  # Use gzip compression
    remove: no  # Set to 'yes' to remove the original files after archiving
  register: config_archive_result

- name: Create /tmp/bla
  tags:
    - backup_config
    - backup_data
    - restore_config
    - restore_data
  file:
    path: "/tmp/bla"
    state: directory
    mode: '0755'

- name: Extract configuration archive to /tmp
  tags:
    - backup_config
  unarchive:
    src: "{{ node_temp }}/{{ inventory_hostname }}-config.zip"
    dest: "/tmp/bla"
    remote_src: yes

- name: Transfer configuration archive to central server
  tags:
    - backup_config
  fetch:
    src: "{{ node_temp }}/{{ inventory_hostname }}-config.tar.gz"
    dest: "{{ storage_temp }}/{{ inventory_hostname }}-config.tar.gz"
    flat: yes
  register: fetch_config_archive_result

- name: Archive nodes config into zip of zips
  tags:
    - backup_config
  shell: (cd {{ storage_temp }} && tar -czf {{ backup_config_archive }} ./)
  delegate_to: localhost
  run_once: true
  register: zip_of_zips_results

