---
# roles/backup/tasks/backup_config.yml

- name: Cleanup temporary directory on nodes
  file:
    path: "{{ node_temp }}"
    state: absent
  register: node_temp_cleanup_results

- name: Create temporary directory on nodes
  file:
    path: "{{ node_temp }}/{{ inventory_hostname }}"
    state: directory
    mode: '0755'

- name: Cleanup temporary directory on localhost
  file:
    path: "{{ storage_temp }}"
    state: absent
  run_once: true

- name: Create temporary directory on localhost
  file:
    path: "{{ storage_temp }}"
    state: directory
    mode: '0755'
  run_once: true

- name: Archive configuration files on nodes
  shell: >
    (cd {{ node_temp }} && tar -czf {{ inventory_hostname }}-config.tar.gz {{ inventory_hostname }})
  register: config_archive_result

- name: Transfer configuration archive to central server
  fetch:
    src: "{{ node_temp }}/{{ inventory_hostname }}-config.tar.gz"
    dest: "{{ storage_temp }}/{{ inventory_hostname }}-config.tar.gz"
    flat: yes

- name: Archive all configuration archives into zip-of-zips
  shell: >
    (cd {{ storage_temp }} && tar -czf {{ backup_config_archive }} ./)
  run_once: true