---
- name: Archive cluster configuration files on nodes
  tags:
    - backup_config
  community.general.archive:
    path: "{{ node_config }}/"  # The directory or files to be archived
    dest: "{{ node_temp }}/{{ inventory_hostname }}-config.zip"  # Destination archive
    format: zip  # Use gzip compression
    remove: no  # Set to 'yes' to remove the original files after archiving
  register: config_archive_result

- name: Transfer configuration archive to central server
  tags:
    - backup_config
  fetch:
    src: "{{ node_temp }}/{{ inventory_hostname }}-config.zip"
    dest: "{{ storage_temp }}/{{ inventory_hostname }}-config.zip"
    flat: yes
  register: fetch_config_archive_result

- name: Create backup folders
  tags:
    - backup_config
  delegate_to: localhost
  run_once: true
  file:
    path: "{{ backup_config_path }}"
    state: directory
    mode: '0755'

- name: Archive nodes config into zip of zips
  tags:
    - backup_config
  delegate_to: localhost
  run_once: true
  community.general.archive:
    path: "{{ storage_temp }}"  # The directory or files to be archived
    dest: "{{ backup_config_archive }}"  # Destination archive
    format: zip  # Use gzip compression
    remove: yes  # Set to 'yes' to remove the original files after archiving
  register: zip_of_zips_results
