---
# Include containers_stop tasks
- name: Stop containers before backing up data
  tags:
    - backup_data
  include_tasks: ../../docker/tasks/stop.yml

- name: Archive cluster data files on nodes
  tags:
    - backup_data
  community.general.archive:
    path: "{{ node_data }}/"  # The directory or files to be archived
    dest: "{{ node_temp }}/{{ inventory_hostname }}-data.tar.zx"  # Destination archive
    format: xz  # Use XZ compression
    remove: no  # Set to 'yes' to remove the original files after archiving
  register: config_archive_result

# Include containers_start tasks
- name: Start containers after backing up data
  tags:
    - backup_data
  include_tasks: ../../docker/tasks/start.yml

- name: Transfer data archive to central server
  tags:
    - backup_data
  fetch:
    src: "{{ node_temp }}/{{ inventory_hostname }}-data.tar.zx"
    dest: "{{ storage_temp }}/{{ inventory_hostname }}-data.tar.zx"
    flat: yes
  register: fetch_data_archive_result

- name: Create backup folders
  tags:
    - backup_data
  delegate_to: localhost
  run_once: true
  file:
    path: "{{ backup_data_path }}"
    state: directory
    mode: '0755'

- name: Archive nodes data into zip of zips
  tags:
    - backup_data
  delegate_to: localhost
  run_once: true
  community.general.archive:
    path: "{{ storage_temp }}/"  # The directory or files to be archived
    dest: "{{ backup_data_archive }}"  # Destination archive
    format: xz  # Use XZ compression
    remove: yes  # Set to 'yes' to remove the original files after archiving
  register: zip_of_zips_results
