---
- name: Archive cluster data files on nodes
  tags: backup_data
  shell: (cd {{ node_data }} && tar -czf {{ node_temp }}/{{ inventory_hostname }}-data.tar.gz ./)
  register: data_archive_result

- name: Transfer data archive to central server
  tags: backup_data
  fetch:
    src: "{{ node_temp }}/{{ inventory_hostname }}-data.tar.gz"
    dest: "{{ storage_temp }}/{{ inventory_hostname }}-data.tar.gz"
    flat: yes
  register: fetch_data_archive_result

- name: Archive nodes data into zip of zips
  tags: backup_data
  shell: (cd {{ storage_temp }} && tar -czf {{ backup_data_archive }} ./)
  delegate_to: localhost
  run_once: true
  register: zip_of_zips_results

