---
- name: Rotate old backups
  tags: rotate_backups
  find:
    paths: "{{ storage_cold }}/rotated"
    age: "{{ retention_policy }}d"
    recurse: yes
    patterns: "*.tar.gz"
  register: old_backups

- name: Remove old backups
  tags: rotate_backups
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ old_backups.files }}"
