# === Nodes startup and shutdown order =================================================================================

docker_run_role_controllers: "{{ inventory_dir }}/templates/docker_command_controllers.j2"
docker_run_role_brokers: "{{ inventory_dir }}/templates/docker_command_brokers.j2"
docker_run_role_connect: "{{ inventory_dir }}/templates/docker_command_connect.j2"

# Defines the order of starting cluster nodes.
startup_order:
  - node-1
  - node-2
  - node-3
  - node-4
  - node-5
  - node-6
  - node-7
  - node-8
  - node-9

# Defines the order of shutting down cluster nodes.
shutdown_order:
  - node-9
  - node-8
  - node-7
  - node-6
  - node-5
  - node-4
  - node-3
  - node-2
  - node-1

