# === Nodes startup and shutdown order =================================================================================

# Defines the order of starting cluster nodes.
startup_order:
  - node-1
  - node-2
  - node-3
  - node-4
  - node-5
  - node-6
  - node-7
  - node-8
  - node-9

# Defines the order of shutting down cluster nodes.
shutdown_order:
  - node-9
  - node-8
  - node-7
  - node-6
  - node-5
  - node-4
  - node-3
  - node-2
  - node-1

docker_command_containers_run: |
  docker run -d --restart=always \
  --name={{ hostvars['inventory_hostname']['hostname'] }} -h {{ hostvars['inventory_hostname']['hostname'] }} \
  -p {{ hostvars[inventory_hostname]['port_jmx_monitoring_ext'] }}:{{ hostvars[inventory_hostname]['port_jmx_monitoring_int'] }} \
  -p {{ hostvars[inventory_hostname]['port_control_plane_ext'] }}:{{ hostvars[inventory_hostname]['port_control_plane_int'] }} \
  -p {{ hostvars[inventory_hostname]['port_replication_ext'] }}:{{ hostvars[inventory_hostname]['port_replication_int'] }} \
  -p {{ hostvars[inventory_hostname]['port_consumer_mtls_ext'] }}:{{ hostvars[inventory_hostname]['port_consumer_mtls_int'] }} \
  -p {{ hostvars[inventory_hostname]['port_consumer_sasl_ext'] }}:{{ hostvars[inventory_hostname]['port_consumer_sasl_int'] }} \
  -e KAFKA_HEAP_OPTS="-Xmx2G -Xms2G" \
  -e KAFKA_JMX_OPTS=" \
  -Djava.rmi.server.hostname={{ hostvars[inventory_hostname]['ansible_host'] }} \
  -Dcom.sun.management.jmxremote \
  -Dcom.sun.management.jmxremote.port={{ hostvars[inventory_hostname]['port_jmx_monitoring_int'] }} \
  -Dcom.sun.management.jmxremote.rmi.port={{ hostvars[inventory_hostname]['port_jmx_monitoring_int'] }} \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -Dcom.sun.management.jmxremote.ssl=false \
  " \
  -v {{ hostvars[inventory_hostname]['node_config_path'] }}:/mnt/shared/config \
  -v {{ hostvars[inventory_hostname]['node_certificate_path'] }}:/etc/kafka/secrets \
  -v {{ hostvars[inventory_hostname]['node_credentials_path'] }}:/credentials \
  -v {{ hostvars[inventory_hostname]['node_data_path'] }}:/var/lib/kafka/data \
  -v {{ hostvars[inventory_hostname]['node_meta_path'] }}:/var/lib/kafka/meta \
  -v {{ hostvars[inventory_hostname]['node_logs_path'] }}:/opt/kafka/logs \
  apache/kafka:3.9.0 \
  /opt/kafka/bin/kafka-server-start.sh /mnt/shared/config/kraft.properties