# === Nodes startup and shutdown order =================================================================================

# Defines the order of starting cluster nodes.
startup_order:
  - node-1
  - node-2
  - node-3
  - node-4
  - node-5
  - node-6
  - node-7
  - node-8
  - node-9

# Defines the order of shutting down cluster nodes.
shutdown_order:
  - node-9
  - node-8
  - node-7
  - node-6
  - node-5
  - node-4
  - node-3
  - node-2
  - node-1

# === Docker commands ==================================================================================================

# Run the kafka roles
docker_run_role:
  controllers: {{ docker_command_controllers}}
  brokers: {{ docker_command_brokers }}
  connect: {{ docker_command_connect }}

docker_run_data_format: {{ docker_command_data_format }}
