---
- name: Create folder for cold rotated backups
  tags:
    - configs_backup
  delegate_to: node-0
  run_once: true
  file:
    path: "{{ central_config_backup_path }}"
    state: directory
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_configs }}"

- name: Create folder for cold pinned backups
  tags:
    - configs_backup
  delegate_to: node-0
  run_once: true
  file:
    path: "{{ central_config_backup_pinned }}"
    state: directory
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_configs }}"

- name: Create configs archive on nodes
  tags:
    - configs_backup
  ansible.builtin.shell:
    cmd: >
      tar -cf - -C {{ node_config_path }} ./ | xz > {{ node_config_temp_archive }}

- name: Pull configs archive from nodes
  tags:
    - configs_backup
  delegate_to: node-0
  synchronize:
    src: "{{ node_config_temp_archive }}"
    dest: "{{ central_config_temp_archive }}"
    mode: pull
    rsync_opts:
      - "--timeout=60"
      - "--checksum"

- name: Create configs zip of zips
  tags:
    - configs_backup
  delegate_to: node-0
  run_once: true
  ansible.builtin.shell:
    cmd: >
      tar -cf - -C {{ storage_temp_path }} ./ | xz > "{{ config_backup_file }}"
