---
- name: Ensure temporal folder on central exists
  tags:
    - config_backup
    - config_restore
    - data_backup
    - data_restore
  delegate_to: kafka-node-0
  run_once: true
  file:
    path: "{{ storage_temp }}"
    state: directory
    mode: '0755'

- name: Ensure temporal folder on nodes exists
  tags:
    - config_backup
    - config_restore
    - data_backup
    - data_restore
  file:
    path: "{{ node_temp }}"
    state: directory
    mode: '0755'
