# === Nodes startup and shutdown order =================================================================================

# Defines the order of starting cluster nodes.
startup_order:
  - node-1
  - node-2
  - node-3
  - node-4
  - node-5
  - node-6

# Defines the order of shutting down cluster nodes.
shutdown_order:
  - node-6
  - node-5
  - node-4
  - node-3
  - node-2
  - node-1

# === Docker commands ==================================================================================================

# Run the nodes (all roles use the same command)
docker_command_containers_run: >
  docker run -d --restart=always --name={{ item }} -h {{ item }}
  -p {{ hostvars[item]['port_service_ext'] }}:{{ hostvars[item]['port_service_int'] }}
  -p {{ hostvars[item]['port_monitoring_ext'] }}:{{ hostvars[item]['port_monitoring_int'] }}
  -e KAFKA_HEAP_OPTS="-Xmx2G -Xms2G"
  -e KAFKA_JMX_OPTS="
  -Dcom.sun.management.jmxremote 
  -Dcom.sun.management.jmxremote.port={{ hostvars[item]['port_monitoring_int'] }}
  -Djava.rmi.server.hostname={{ hostvars[item]['ansible_host'] }}
  -Dcom.sun.management.jmxremote.rmi.port={{ hostvars[item]['port_monitoring_int'] }}
  -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
  "
  -e KAFKA_OPTS="
  -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
  "
  -v {{ hostvars[item]['node_config_file'] }}:/etc/kafka/server.properties
  -v {{ hostvars[item]['node_credentials_file'] }}:/etc/kafka/kafka_server_jaas.conf
  -v {{ hostvars[item]['node_data_path'] }}:/var/lib/kafka/data
  -v {{ hostvars[item]['node_logs_path'] }}:/var/log/kafka
  -v {{ hostvars[item]['node_certificate_path'] }}:/etc/kafka/ssl
  confluentinc/cp-kafka:7.8.0
  /usr/bin/kafka-server-start /etc/kafka/server.properties

# Empty folder should be prepared for usage
docker_command_data_format: >
  docker run --rm
  -v {{ node_config_file }}:/etc/kafka/server.properties
  -v {{ node_data_path }}:/var/lib/kafka/data
  -v {{ node_logs_path }}:/var/log/kafka
  -v {{ node_certificate_path }}:/etc/kafka/ssl
  confluentinc/cp-kafka:7.8.0
  /usr/bin/kafka-storage format 
  --add-scram 'SCRAM-SHA-256=[name=admin,password=insecure]' 
  --cluster-id {{ cluster_id }} 
  --config /etc/kafka/server.properties
