# === Restore archive parameter ========================================================================================

# Path to the restore archive (to be provided via CLI parameters). Should be an absolute file path.
restore_archive: ""

# === Node Permissions =================================================================================================

# Service user
data_owner_user: 1000

# Service group
data_owner_group: 1000

# Data folder permissions
data_folder_chmod: 0755

# Credentials file permissions
credentials_folder_chmod: 0600

# === Node Restore & Generate Locations ================================================================================

# cluster node's certificate files.
node_certificate_path: "/data/cluster/certificate"

# cluster node's credentials file.
node_credentials_path: "/data/cluster/credentials"
# cluster node's credentials file.
node_credentials_file: "{{ node_credentials_path }}/kafka_server_jaas.conf"

# cluster node's config files.
node_config_path: "/data/cluster/config"
# cluster node's config files.
node_config_file: "{{ node_config_path }}/kraft.properties"

# cluster node's data files.
node_data_path: "/data/cluster/data"

# cluster node's logs files.
node_logs_path: "/data/cluster/logs"

# Temporary directory on nodes for extracting & creating archives for backups & restores.
node_temp_path: "/data/temp"
