---
- name: Check if GNU tar is installed
  ansible.builtin.command: tar --version
  register: tar_check
  failed_when: tar_check.rc != 0
  changed_when: false
  ignore_errors: true
  tags: prerequisites

- name: Ensure GNU tar is installed
  ansible.builtin.package:
    name: tar
    state: present
  when: tar_check is failed
  tags: prerequisites

- name: Validate GNU tar installation
  ansible.builtin.command: tar --version
  failed_when: tar_check.rc != 0
  changed_when: false
  tags: prerequisites

- name: Check if gzip is installed
  ansible.builtin.command: gzip --version
  register: gzip_check
  failed_when: gzip_check.rc != 0
  changed_when: false
  ignore_errors: true
  tags: prerequisites

- name: Ensure gzip is installed
  ansible.builtin.package:
    name: gzip
    state: present
  when: gzip_check is failed
  tags: prerequisites

- name: Validate gzip installation
  ansible.builtin.command: gzip --version
  failed_when: gzip_check.rc != 0
  changed_when: false
  tags: prerequisites

- name: Check if unzip is installed
  ansible.builtin.command: unzip -v
  register: unzip_check
  failed_when: unzip_check.rc != 0
  changed_when: false
  ignore_errors: true
  tags: prerequisites

- name: Ensure unzip is installed
  ansible.builtin.package:
    name: unzip
    state: present
  when: unzip_check is failed
  tags: prerequisites

- name: Validate unzip installation
  ansible.builtin.command: unzip -v
  failed_when: unzip_check.rc != 0
  changed_when: false
  tags: prerequisites

- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_check
  failed_when: docker_check.rc != 0
  changed_when: false
  ignore_errors: true
  tags: prerequisites

- name: Install Docker
  ansible.builtin.package:
    name: docker
    state: present
  when: docker_check is failed
  tags: prerequisites

- name: Validate Docker installation
  ansible.builtin.command: docker --version
  failed_when: docker_check.rc != 0
  changed_when: false
  tags: prerequisites
