---
- name: Archive cluster config on nodes
  tags:
    - config_backup
  community.general.archive:
    path: "{{ node_config }}/"  # The directory or files to be archived
    dest: "{{ node_temp }}/{{ inventory_hostname }}-config.tar.zx"  # Destination archive
    format: xz  # Use XZ compression
    remove: no  # Set to 'yes' to remove the original files after archiving
  register: config_archive_result

- name: Transfer config archive to central server
  tags:
    - config_backup
  fetch:
    src: "{{ node_temp }}/{{ inventory_hostname }}-config.tar.zx"
    dest: "{{ storage_temp }}/{{ inventory_hostname }}-config.tar.zx"
    flat: yes
  register: fetch_config_archive_result

- name: Create backup path folders
  tags:
    - config_backup
  delegate_to: kafka-node-0
  run_once: true
  file:
    path: "{{ config_backup_path }}"
    state: directory
    mode: '0755'

- name: Archive cluster config into zip of zips
  tags:
    - config_backup
  delegate_to: kafka-node-0
  run_once: true
  community.general.archive:
    path: "{{ storage_temp }}/"  # The directory or files to be archived
    dest: "{{ config_backup_archive }}"  # Destination archive
    format: xz  # Use XZ compression
    remove: yes  # Set to 'yes' to remove the original files after archiving
  register: zip_of_zips_results
