---
- name: Ensure Config directory exists
  tags:
    - config_deploy
  ansible.builtin.file:
    path: "{{ node_config_path }}"
    state: directory
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: '{{ chmod_config }}'

- name: Determine the group for the host dynamically
  tags: config_deploy
  set_fact:
    relevant_group: "{{ item }}"
  with_items: "{{ group_names }}"
  when: item not in ['all', 'cluster', 'central']
  run_once: false

- name: Determine the template dynamically based on the group
  tags: config_deploy
  set_fact:
    selected_template: "{{ inventory_dir }}/templates/server_properties_{{ relevant_group }}.j2"

- name: Deploy configuration file for the host
  tags: config_deploy
  template:
    src: "{{ selected_template }}"
    dest: "{{ node_config_file }}"
