# === Nodes involved in the cluster definition  ========================================================================
all:
  children:
    central:
      hosts:
        node-0:
          ansible_host: 10.1.3.20
          hostname: Node-0.intel.r7g.org
    cluster:
      children:
        controllers:
          hosts:
            node-1:
              ansible_host: 10.1.3.21
              hostname: Node-1.intel.r7g.org
              node_id: 1
            node-2:
              ansible_host: 10.1.3.22
              hostname: Node-2.intel.r7g.org
              node_id: 2
            node-3:
              ansible_host: 10.1.3.23
              hostname: Node-3.intel.r7g.org
              node_id: 3
        brokers:
          hosts:
            node-4:
              ansible_host: 10.1.3.24
              hostname: Node-4.intel.r7g.org
              node_id: 4
            node-5:
              ansible_host: 10.1.3.25
              hostname: Node-5.intel.r7g.org
              node_id: 5
            node-6:
              ansible_host: 10.1.3.26
              hostname: Node-6.intel.r7g.org
              node_id: 6
        connect:
          hosts:
            node-7:
              ansible_host: 10.1.3.27
              hostname: Node-7.intel.r7g.org
              node_id: 7
            node-8:
              ansible_host: 10.1.3.28
              hostname: Node-8.intel.r7g.org
              node_id: 8
            node-9:
              ansible_host: 10.1.3.29
              hostname: Node-9.intel.r7g.org
              node_id: 9
