---
- name: Verify certificate fullchain present on central
  tags:
    - cert_deploy
  delegate_to: kafka-node-0
  run_once: true
  stat:
    path: "{{ certificate_file_fullchain }}"
  register: cert_stat_fullchain

- name: Fail if certificate fullchain does not exist
  tags:
    - cert_deploy
  delegate_to: kafka-node-0
  run_once: true
  fail:
    msg: "The specified certificate fullchain {{ certificate_file_fullchain }} does not exist!"
  when: not cert_stat_fullchain.stat.exists

- name: Verify certificate key present on central
  tags:
    - cert_deploy
  delegate_to: kafka-node-0
  run_once: true
  stat:
    path: "{{ certificate_file_key }}"
  register: cert_stat_key

- name: Fail if certificate key does not exist
  tags:
    - cert_deploy
  delegate_to: kafka-node-0
  run_once: true
  fail:
    msg: "The specified certificate key {{ certificate_file_key }} does not exist!"
  when: not cert_stat_key.stat.exists

- name: Verify certificate CA present on central
  tags:
    - cert_deploy
  delegate_to: kafka-node-0
  run_once: true
  stat:
    path: "{{ certificate_file_ca }}"
  register: cert_stat_ca

- name: Fail if certificate CA does not exist
  tags:
    - cert_deploy
  delegate_to: kafka-node-0
  run_once: true
  fail:
    msg: "The specified certificate CA {{ certificate_file_ca }} does not exist!"
  when: not cert_stat_ca.stat.exists

- name: Extract certificate expiration details
  tags:
    - cert_deploy
  delegate_to: kafka-node-0
  run_once: true
  shell: |
    cert_date=$(openssl x509 -enddate -noout -in {{ certificate_file_fullchain }} | sed 's/^notAfter=//')
    cert_epoch=$(date -d "$cert_date" +%s)
    current_epoch=$(date +%s)
    cert_days_remaining=$(( (cert_epoch - current_epoch) / 86400 ))
    echo "expiration_date=$cert_date"
    echo "expiration_epoch=$cert_epoch"
    echo "days_remaining=$cert_days_remaining"
  register: cert_details

- name: Parse certificate expiration details
  tags:
    - cert_deploy
  delegate_to: kafka-node-0
  run_once: true
  set_fact:
    certificate_expiration_date: "{{ cert_details.stdout_lines | select('search', '^expiration_date=') | map('regex_replace', '^expiration_date=', '') | first }}"
    certificate_expiration_epoch: "{{ cert_details.stdout_lines | select('search', '^expiration_epoch=') | map('regex_replace', '^expiration_epoch=', '') | first | int }}"
    certificate_expire_in_days: "{{ cert_details.stdout_lines | select('search', '^days_remaining=') | map('regex_replace', '^days_remaining=', '') | first | int }}"

- name: Debug certificate expiration details
  tags:
    - cert_deploy
  delegate_to: kafka-node-0
  run_once: true
  debug:
    msg: >
      Raw expiration date: {{ certificate_expiration_date }}.
      Expiration epoch time: {{ certificate_expiration_epoch }}.
      Days until expiration: {{ certificate_expire_in_days }}.

- name: Fail if certificate is expired or expires soon
  tags:
    - cert_deploy
  delegate_to: kafka-node-0
  run_once: true
  fail:
    msg: >
      {% if certificate_expire_in_days | float == 0 %}
      The specified certificate fullchain {{ certificate_file_fullchain }} expires today!
      {% elif certificate_expire_in_days | float < 0 %}
      The specified certificate fullchain {{ certificate_file_fullchain }} expired {{ certificate_expire_in_days | float | abs | round(2) }} days ago!
      {% else %}
      The specified certificate fullchain {{ certificate_file_fullchain }} will expire in {{ certificate_expire_in_days  | float | round(2) }} days!
      {% endif %}
  when: certificate_expire_in_days | float < 30

- name: Generate KeyStore
  tags:
    - cert_deploy
  delegate_to: kafka-node-0
  run_once: true
  shell: >
    openssl pkcs12 -export
    -in {{ certificate_file_fullchain }}
    -inkey {{ certificate_file_key }}
    -out {{ certificate_file_p12 }}
    -name {{ certificate_host }}
    -password pass:keystorepassword
