---
- name: Deploy SSH public keys on all cluster nodes
  include_tasks: ssh_keys.yml
  tags:
    - ssh_keys

- name: Install prerequisites on all cluster nodes
  include_tasks: prerequisites.yml
  tags:
    - prerequisites
