---
- name: Check if XZ is installed
  tags: prerequisites
  ansible.builtin.shell: command -v xz
  register: xz_check
  failed_when: xz_check.rc != 0 and false
  changed_when: false
  ignore_errors: true

- name: Notify if XZ is missing
  tags: prerequisites
  ansible.builtin.debug:
    msg: "XZ is missing on {{ inventory_hostname }}. It will be installed in a moment."
  when: xz_check.rc != 0

- name: Ensure XZ is installed
  tags: prerequisites
  ansible.builtin.package:
    name: "{{ 'xz-utils' if ansible_os_family == 'Debian' else 'xz' }}"
    state: present
  when: xz_check.rc != 0

- name: Validate XZ installation
  tags: prerequisites
  ansible.builtin.command: xz --version
  register: xz_validate
  changed_when: false

- name: Check if Java is installed
  tags: prerequisites
  ansible.builtin.shell: command -v java
  register: java_check
  failed_when: java_check.rc != 0 and false
  changed_when: false
  ignore_errors: true

- name: Notify if Java is missing
  tags: prerequisites
  ansible.builtin.debug:
    msg: "Java is missing on {{ inventory_hostname }}. It will be installed in a moment."
  when: java_check.rc != 0

- name: Ensure Java is installed
  tags: prerequisites
  ansible.builtin.package:
    name: "{{ 'default-jre' if ansible_os_family == 'Debian' else 'java-1.8.0-openjdk' }}"
    state: present
  when: java_check.rc != 0

- name: Validate Java installation
  tags: prerequisites
  ansible.builtin.command: java -version
  register: java_validate
  failed_when: java_check.rc != 0 and false
  changed_when: false

- name: Check if Docker is installed
  tags: prerequisites
  ansible.builtin.command: docker --version
  register: docker_check
  failed_when: docker_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Install Docker
  tags: prerequisites
  ansible.builtin.package:
    name: docker
    state: present
  when: docker_check is failed

- name: Validate Docker installation
  tags: prerequisites
  ansible.builtin.command: docker --version
  failed_when: docker_check.rc != 0
  changed_when: false

- name: Check if rsync is installed
  tags: prerequisites
  ansible.builtin.command: rsync --version
  register: rsync_check
  failed_when: rsync_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Ensure rsync is installed
  tags: prerequisites
  ansible.builtin.package:
    name: rsync
    state: present
  when: rsync_check is failed

- name: Validate rsync installation
  tags: prerequisites
  ansible.builtin.command: rsync --version
  failed_when: rsync_check.rc != 0
  changed_when: false
