---
- name: Check if XZ is installed
  tags: prerequisites
  ansible.builtin.command: xz --version
  register: xz_check
  failed_when: xz_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Ensure XZ is installed
  tags: prerequisites
  ansible.builtin.package:
    name: "{{ 'xz-utils' if ansible_os_family == 'Debian' else 'xz' }}"
    state: present
  when: xz_check.rc != 0

- name: Validate xz installation
  tags: prerequisites
  ansible.builtin.command: xz --version
  failed_when: xz_check.rc != 0
  changed_when: false

- name: Check if Java is installed
  tags: prerequisites
  ansible.builtin.command: java -version
  register: java_check
  failed_when: java_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Ensure Java is installed
  tags: prerequisites
  ansible.builtin.package:
    name: default-jre
    state: present
  when: java_check is failed

- name: Validate Java installation
  tags: prerequisites
  ansible.builtin.command: java -version
  failed_when: java_check.rc != 0
  changed_when: false

- name: Check if Docker is installed
  tags: prerequisites
  ansible.builtin.command: docker --version
  register: docker_check
  failed_when: docker_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Install Docker
  tags: prerequisites
  ansible.builtin.package:
    name: docker
    state: present
  when: docker_check is failed

- name: Validate Docker installation
  tags: prerequisites
  ansible.builtin.command: docker --version
  failed_when: docker_check.rc != 0
  changed_when: false

- name: Check if rsync is installed
  tags: prerequisites
  ansible.builtin.command: rsync --version
  register: rsync_check
  failed_when: rsync_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Ensure rsync is installed
  tags: prerequisites
  ansible.builtin.package:
    name: rsync
    state: present
  when: rsync_check is failed

- name: Validate rsync installation
  tags: prerequisites
  ansible.builtin.command: rsync --version
  failed_when: rsync_check.rc != 0
  changed_when: false
