---
- name: Ensure SSH directory exists on the remote host
  tags: ssh_keys
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Copy public key to the remote server
  tags: ssh_keys
  ansible.builtin.shell: |
    echo "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" >> ~/.ssh/authorized_keys
  args:
    executable: /bin/bash

- name: Set proper permissions on authorized_keys
  tags: ssh_keys
  ansible.builtin.file:
    path: ~/.ssh/authorized_keys
    mode: '0600'

- name: Test passwordless SSH access
  tags: ssh_keys
  ansible.builtin.shell: |
    ssh -o PasswordAuthentication=no {{ ansible_host }} "echo 'Passwordless SSH setup complete'"
  ignore_errors: true
