---
- name: Remove temporal folder on central
  tags:
    - config_backup
    - config_restore
    - data_backup
    - data_restore
    - temp_cleanup
  delegate_to: node-0
  run_once: true
  file:
    path: "{{ storage_temp }}"
    state: absent

- name: Create temporal folder on central
  tags:
    - config_backup
    - config_restore
    - data_backup
    - data_restore
    - temp_cleanup
  delegate_to: node-0
  run_once: true
  file:
    path: "{{ storage_temp }}"
    state: directory
    mode: '0755'

- name: Remove temporal folder on nodes
  tags:
    - config_backup
    - config_restore
    - data_backup
    - data_restore
    - temp_cleanup
  file:
    path: "{{ node_temp }}"
    state: absent

- name: Create temporal folder on nodes
  tags:
    - config_backup
    - config_restore
    - data_backup
    - data_restore
    - temp_cleanup
  file:
    path: "{{ node_temp }}"
    state: directory
    mode: '0755'