---
- name: Remove temporal folder on central
  delegate_to: node-0
  run_once: true
  file:
    path: "{{ storage_temp_path }}"
    state: absent

- name: Create temporal folder on central
  delegate_to: node-0
  run_once: true
  file:
    path: "{{ storage_temp_path }}"
    state: directory
    mode: '0755'

- name: Remove temporal folder on nodes
  file:
    path: "{{ node_temp_path }}"
    state: absent

- name: Create temporal folder on nodes
  file:
    path: "{{ node_temp_path }}"
    state: directory
    mode: '0755'