---
- name: Stop Docker containers in shutdown order
  tags:
    - containers_stop
    - containers_restart
  shell: docker stop {{ item }}
  delegate_to: "{{ item }}"
  with_items: "{{ shutdown_order }}"
  run_once: true  # Ensure task runs only once on localhost
