---
- name: Start Docker containers in startup order
  tags:
    - containers_start
    - containers_restart
  shell: docker start {{ item }}
  delegate_to: "{{ item }}"
  with_items: "{{ startup_order }}"
  run_once: true  # Ensure task runs only once on localhost