---
- name: Check if the containers are running
  tags:
    - containers_validation
    - data_backup
    - data_format
    - data_restore
  shell: "docker inspect -f '{{ '{{.State.Running}}' }}' {{ hostvars[item]['hostname'] }}"
  register: container_status
  ignore_errors: yes

- name: Container status output
  tags:
    - containers_validation
    - data_backup
    - data_format
    - data_restore
  debug:
    msg: >
      {% if container_status.stdout == "true" %}
        Error: Container {{ hostvars[item]['hostname'] }} on {{ hostvars[item]['hostname'] }} is still running. Please stop all containers before proceeding.
      {% else %}
        Success: Container {{ hostvars[item]['hostname'] }} on {{ hostvars[item]['hostname'] }} is not running.
      {% endif %}
  failed_when: container_status.stdout == "true"
  any_errors_fatal: true