---
- name: Check if the containers are running
  tags:
    - containers_validation
    - data_backup
    - data_format
    - data_restore
  shell: "docker inspect -f '{{ '{{.State.Running}}' }}' {{ inventory_hostname  }}"
  register: container_status
  ignore_errors: yes

- name: Container status output
  tags:
    - containers_validation
    - data_backup
  debug:
    msg: >
      {% if container_status.stdout == "true" %}
        Error: Container {{ inventory_hostname }} on {{ ansible_host }} is still running. Please stop all containers before proceeding.
      {% else %}
        Success: Container {{ inventory_hostname }} on {{ ansible_host }} is stopped.
      {% endif %}
  failed_when: container_status.stdout == "true"
  any_errors_fatal: true