---
- name: Collect all group names for nodes
  tags:
    - containers_run
  set_fact:
    group_names_all: "{{ group_names_all | default({}) | combine({item: hostvars[item]['group_names']}) }}"
  with_items: "{{ startup_order }}"
  run_once: true

- name: Run Docker containers in startup order based on group
  tags:
    - containers_run
  shell: "{{ docker_run_role[host_group] }}"
  delegate_to: "{{ item }}"
  with_items: "{{ startup_order }}"
  run_once: true
  vars:
    host_group: "{{ (group_names_all[item] | difference(['all', 'cluster', 'central']))[0] | default('undefined_group') }}"
  when: host_group in docker_run_role


#- name: Run docker containers in startup order
#  tags:
#    - containers_run
#  shell: "{{ docker_command_containers_run }}"
#  delegate_to: "{{ item }}"
#  with_items: "{{ startup_order }}"
#  run_once: true  # Ensure task runs only once on localhost
