---
- name: Run docker containers in startup order
  tags:
    - containers_run
  shell: "{{ docker_command_containers_run }}"
  delegate_to: "{{ item }}"
  with_items: "{{ startup_order }}"
  run_once: true  # Ensure task runs only once on localhost
