---
# Include containers_stop tasks
- name: Stop containers before backing up data
  tags:
    - backup_data
  include_tasks: stop.yml

# Include containers_start tasks
- name: Start containers after backing up data
  tags:
    - backup_data
  include_tasks: start.yml
