---
- name: Stop Docker containers in shutdown order
  tags:
    - containers_stop
    - backup_data
    - restore_data
  shell: docker stop {{ inventory_hostname }}
  with_items: "{{ shutdown_order }}"
  when: inventory_hostname == item
