---
- name: Stop Docker containers in shutdown order
  tags:
    - containers_stop
    - containers_restart
    - data_backup
    - data_restore
  shell: docker stop {{ inventory_hostname }}
  with_items: "{{ shutdown_order }}"
  when: inventory_hostname == item
