---
- name: Stop Docker containers in shutdown order (one by one)
  shell: docker stop {{ item }}
  with_items: "{{ shutdown_order }}"
  delegate_to: "{{ item }}"
  register: stop_results

- name: Debug container stop results
  debug:
    msg: "Container {{ item.item }} stop result: {{ item.rc == 0 | ternary('success', 'failure') }}"
  with_items: "{{ stop_results.results }}"
