---
- name: Stop Docker containers in shutdown order (one by one)
  shell: docker stop {{ item }}
  with_items: "{{ shutdown_order }}"
  when: inventory_hostname == item
  register: stop_results
  run_once: true
  serial: 1

- name: Debug container stop status
  debug:
    var: stop_results.results
