all:
  children:
    central:
      hosts:
        node-0:
          ansible_host: 10.1.3.20
    cluster:
      hosts:
        node-1:
          ansible_host: 10.1.3.21
          node_id: 1
          roles:
            - broker
            - controller
        node-2:
          ansible_host: 10.1.3.22
          node_id: 2
          roles:
            - broker
            - controller
        node-3:
          ansible_host: 10.1.3.23
          node_id: 3
          roles:
            - broker
            - controller
