all:
  children:
    central:
      hosts:
        node-0:
          ansible_host: 10.1.3.20
          hostname: node-0.intel.r7g.org
    cluster:
      children:
        controllers:
        brokers:
        combined:
          hosts:
            node-1:
              ansible_host: 10.1.3.21
              hostname: node-1.intel.r7g.org
              port_controller_ext: 9093
              node_id: 1
            node-2:
              ansible_host: 10.1.3.22
              hostname: node-2.intel.r7g.org
              node_id: 2
            node-3:
              ansible_host: 10.1.3.23
              hostname: node-3.intel.r7g.org
              node_id: 3