# === Nodes involved in the cluster definition  ========================================================================
all:
  children:
    central:
      hosts:
        node-00:
          ansible_host: 54.90.172.203
          hostname: ec2-kafka-outburn.r7g.org
          node_config_path: /data/single-node/balancer
          port_jmx_monitoring_ext: 9990
    cluster:
      children:
        controllers:
          hosts:
            node-01:
              ansible_host: 54.90.172.203
              hostname: controller-ec2-kafka-outburn.r7g.org
              node_id: 1
              node_storage_base: /data/single-node/controller
              node_temp_path: /data/single-node/controller/temp
              port_jmx_monitoring_ext: 9991
        brokers:
          hosts:
            node-02:
              ansible_host: 54.90.172.203
              hostname: broker-ec2-kafka-outburn.r7g.org
              node_id: 2
              node_storage_base: /data/single-node/broker
              node_temp_path: /data/single-node/broker/temp
              port_jmx_monitoring_ext: 9992
        schema:
          hosts:
            node-03:
              ansible_host: 54.90.172.203
              hostname: connect-ec2-kafka-outburn.r7g.org
              node_id: 3
              node_storage_base: /data/single-node/schema
              node_temp_path: /data/single-node/schema/temp
              port_jmx_monitoring_ext: 9993
        connect:
          hosts:
            node-04:
              ansible_host: 54.90.172.203
              hostname: connect-ec2-kafka-outburn.r7g.org
              node_id: 4
              node_storage_base: /data/single-node/connect
              node_temp_path: /data/single-node/connect/temp
              port_jmx_monitoring_ext: 9994
        ksql:
          hosts:
            node-05:
              ansible_host: 54.90.172.203
              hostname: connect-ec2-kafka-outburn.r7g.org
              node_id: 5
              node_storage_base: /data/single-node/ksql
              node_temp_path: /data/single-node/ksql/temp
              port_jmx_monitoring_ext: 9995
