# === Nodes involved in the cluster definition  ========================================================================
all:
  children:
    central:
      hosts:
        node-0:
          ansible_host: 172.31.16.179
          hostname: ec2-kafka-outburn.r7g.org
    cluster:
      children:
        controllers:
          hosts:
            node-1:
              ansible_host: 172.31.16.179
              hostname: controller-ec2-kafka-outburn.r7g.org
              node_id: 1
              node_storage_base: /data/single-node/controller
        brokers:
          hosts:
            node-2:
              ansible_host: 172.31.16.179
              hostname: broker-ec2-kafka-outburn.r7g.org
              node_id: 2
              node_storage_base: /data/single-node/broker
        connect:
          hosts:
            node-3:
              ansible_host: 172.31.16.179
              hostname: connect-ec2-kafka-outburn.r7g.org
              node_id: 3
              node_storage_base: /data/single-node/connect
