# === Nodes involved in the cluster definition  ========================================================================
all:
  children:
    central:
      hosts:
        node-0:
          ansible_host: 54.90.172.203
          hostname: ec2-kafka-outburn.r7g.org
          node_config_path: /data/single-node/balancer
    cluster:
      children:
        controllers:
          hosts:
            node-1:
              ansible_host: 54.90.172.203
              hostname: controller-ec2-kafka-outburn.r7g.org
              node_id: 1
              node_storage_base: /data/single-node/controller
              node_temp_path: /data/single-node/controller/temp
        brokers:
          hosts:
            node-2:
              ansible_host: 54.90.172.203
              hostname: broker-ec2-kafka-outburn.r7g.org
              node_id: 2
              node_storage_base: /data/single-node/broker
              node_temp_path: /data/single-node/broker/temp
        connect:
          hosts:
            node-3:
              ansible_host: 54.90.172.203
              hostname: connect-ec2-kafka-outburn.r7g.org
              node_id: 3
              node_storage_base: /data/single-node/connect
              node_temp_path: /data/single-node/connect/temp
