---
- name: Cluster Backup Offline
  hosts: cluster
  become: yes
  serial: 6
  pre_tasks:
    - name: Cleanup temp folders before execution
#      tags:
#        - certificate_backup
#        - certificate_restore
#        - config_backup
#        - config_restore
#        - data_backup
#        - data_restore
#        - temp_cleanup
      include_tasks: ../roles/system/tasks/temp_cleanup.yml
  roles:
    - role: ../roles/system       # Include stuff like Prerequisites, temp folder cleanup etc.
    - role: ../roles/certificate  # Include Certificate related tasks
    - role: ../roles/config       # Include Config related tasks
    - role: ../roles/data         # Include Data related tasks
    - role: ../roles/docker       # Include Docker related tasks
  post_tasks:
    - name: Cleanup temp folders after execution
#      tags:
#        - certificate_backup
#        - certificate_restore
#        - config_backup
#        - config_restore
#        - data_backup
#        - data_restore
#        - temp_cleanup
      include_tasks: ../roles/system/tasks/temp_cleanup.yml

- name: Start Docker containers in startup order
  hosts: localhost
  become: yes
  tags: containers_start
  tasks:
    - name: Start Docker containers in defined startup order
      tags: containers_start
      shell: docker start {{ item }}
      delegate_to: "{{ item }}"
      with_items: "{{ startup_order }}"
      run_once: true  # Ensure task runs only once on localhost

- name: Stop Docker containers in shutdown order
  hosts: localhost
  become: yes
  tags: containers_stop
  tasks:
    - name: Stop Docker containers in defined shutdown order
      tags: containers_stop
      shell: docker stop {{ item }}
      delegate_to: "{{ item }}"
      with_items: "{{ shutdown_order }}"
      run_once: true  # Ensure task runs only once on localhost
