---
- name: Manage cluster operations
  hosts: all
  become: yes
  pre_tasks:
    - name: Perform pre-execution steps
      include_tasks: ../roles/common/pre_tasks.yml

  roles:
    - role: ../roles/ssh  # Include SSH-related tasks
    - role: ../roles/docker  # Include Docker-related tasks
    - role: ../roles/backup  # Include Backup and Restore tasks
  tags:
    - ssh_install
    - backup_config
    - backup_data
    - restore_config
    - restore_data
    - wipe_data
    - format_data
    - rotate_backups
    - containers_run
    - containers_stop
    - containers_start
    - containers_restart
    - containers_remove

  post_tasks:
    - name: Perform post-execution cleanup
      include_tasks: ../roles/common/post_tasks.yml
