---
- import_playbook: pre.yml

- name: Manage cluster backup
  hosts: all
  become: yes
  roles:
    - role: ../roles/ssh  # Include SSH-related tasks
    - role: ../roles/docker  # Include Docker-related tasks
    - role: ../roles/backup  # Include Backup and Restore tasks

- import_playbook: post.yml
