---
- name: Cluster Backup Offline
  hosts: nodes
  become: yes

  pre_tasks:
    - name: Cleanup temp folders before execution
      tags:
        - config_backup
        - config_restore
        - data_backup
        - data_restore
        - temp_cleanup
      include_tasks: ../roles/system/tasks/temp_cleanup.yml

  roles:
    - role: ../roles/config         # Include Config related tasks
    - role: ../roles/data           # Include Data related tasks
    - role: ../roles/docker         # Include Docker related tasks
    - role: ../roles/system         # Include stuff like Prerequisites, Config deploy, Certs deploy, temp folder cleanup etc.

  post_tasks:
    - name: Cleanup temp folders after execution
      tags:
        - config_backup
        - config_restore
        - data_backup
        - data_restore
        - temp_cleanup
      include_tasks: ../roles/system/tasks/temp_cleanup.yml