---
- name: Manage cluster backup
  hosts: all
  become: yes

  pre_tasks:
    - name: Cleanup temporary files before execution
      tags:
        - backup_config
        - backup_data
        - restore_config
        - restore_data
      include_tasks: ../roles/common/cleanup.yml

  roles:
    - role: ../roles/ssh  # Include SSH-related tasks
    - role: ../roles/docker  # Include Docker-related tasks
    - role: ../roles/backup  # Include Backup and Restore tasks

  post_tasks:
    - name: Cleanup temporary files after execution
      tags:
        - backup_config
        - backup_data
        - restore_config
        - restore_data
      include_tasks: ../roles/common/cleanup.yml