---
- name: Manage cluster operations
  hosts: all
  become: yes
  pre_tasks:
    - name: Perform pre-execution steps
      tags:
        - backup_data
        - backup_config
      include_tasks: ../roles/common/pre_tasks.yml


  roles:
    - role: ../roles/ssh  # Include SSH-related tasks
    - role: ../roles/docker  # Include Docker-related tasks
    - role: ../roles/backup  # Include Backup and Restore tasks

  post_tasks:
    - name: Perform post-execution cleanup
      tags:
        - backup_data
        - backup_config
      include_tasks: ../roles/common/post_tasks.yml
