---
- name: Cluster Backup Offline
  hosts: cluster
  become: yes
  pre_tasks:
    - name: Cleanup temp folders before execution
      include_tasks: ../roles/system/tasks/temp_cleanup.yml

  roles:
    - role: ../roles/system        # Include stuff like Prerequisites, temp folder cleanup etc.
    - role: ../roles/credentials   # Include Credentials related tasks
    - role: ../roles/certificates  # Include Certificate related tasks
    - role: ../roles/configs       # Include Configs related tasks
    - role: ../roles/data          # Include Data related tasks

  post_tasks:
    - name: Cleanup temp folders after execution
      include_tasks: ../roles/system/tasks/temp_cleanup.yml
      tags:
        - certificates_backup
        - certificates_restore
        - credentials_backup
        - credentials_restore
        - configs_backup
        - configs_restore
        - data_backup
        - data_restore
        - temp_cleanup
