---
- name: Prepare localhost
  hosts: localhost
  become: yes
  tasks:
    - name: Create temporal folder
      tags:
        - backup_config
        - backup_data
      file:
        path: "{{ storage_temp }}"
        state: directory
        mode: '0755'

- name: Prepare nodes
  hosts: nodes
  become: yes
  tasks:
    - name: Create temporal folder
      tags:
        - backup_config
        - backup_data
      file:
        path: "{{ node_temp }}"
        state: directory
        mode: '0755'
