---
- name: Cluster Backup Offline - Serial execution
  hosts: localhost
  serial: 1
  become: yes
  roles:
    - role: ../roles/docker # Include Docker related tasks
    - role: ../roles/system # Include stuff like reboot