# === Nodes involved in the cluster definition  ========================================================================
all:
  children:
    central:
      hosts:
        node-0:
          ansible_host: 10.1.3.20
          hostname: node-0
    cluster:
      children:
        controllers:
          hosts:
            node-1:
              ansible_host: 10.1.3.21
              hostname: node-1
              node_id: 1
            node-2:
              ansible_host: 10.1.3.22
              hostname: node-2
              node_id: 2
            node-3:
              ansible_host: 10.1.3.23
              hostname: node-3
              node_id: 3
        brokers:
          hosts:
            node-4:
              ansible_host: 10.1.3.24
              hostname: node-4
              node_id: 4
            node-5:
              ansible_host: 10.1.3.25
              hostname: node-5
              node_id: 5
            node-6:
              ansible_host: 10.1.3.26
              hostname: node-6
              node_id: 6
