all:
  children:
    central:
      hosts:
        node-0:
          ansible_host: 10.1.3.20
          roles:
            - central
    brokers:
      hosts:
        node-1:
          ansible_host: 10.1.3.21
          roles:
            - broker
        node-2:
          ansible_host: 10.1.3.22
          roles:
            - broker
        node-3:
          ansible_host: 10.1.3.23
          roles:
            - broker
    controllers:
      hosts:
        node-4:
          ansible_host: 10.1.3.24
          roles:
            - controller
        node-5:
          ansible_host: 10.1.3.25
          roles:
            - controller
        node-6:
          ansible_host: 10.1.3.26
          roles:
            - controller
