---
- name: Remove temporal folder on localhost
  tags:
    - config_backup
    - data_backup
    - config_restore
    - data_restore
  delegate_to: localhost
  run_once: true
  file:
    path: "{{ storage_temp }}"
    state: absent

- name: Create temporal folder on localhost
  tags:
    - config_backup
    - data_backup
    - config_restore
    - data_restore
  delegate_to: localhost
  run_once: true
  file:
    path: "{{ storage_temp }}"
    state: directory
    mode: '0755'

- name: Remove temporal folder on nodes
  tags:
    - config_backup
    - data_backup
    - config_restore
    - data_restore
  file:
    path: "{{ node_temp }}"
    state: absent

- name: Create temporal folder on nodes
  tags:
    - config_backup
    - data_backup
    - config_restore
    - data_restore
  file:
    path: "{{ node_temp }}"
    state: directory
    mode: '0755'