---
- name: Cleanup temporal folder on localhost
  tags:
    - backup_config
    - backup_data
    - restore_config
    - restore_data
  delegate_to: localhost
  run_once: true
  shell: rm -rf {{ storage_temp }} && mkdir -p {{ storage_temp }} && chmod 0755 {{ storage_temp }}

- name: Cleanup temporal folder on nodes
  tags:
    - backup_config
    - backup_data
    - restore_config
    - restore_data
  shell: rm -rf {{ node_temp }} && mkdir -p {{ node_temp }} && chmod 0755 {{ node_temp }}
