---
- name: Ensure temporary directory exists on nodes
  file:
    path: "{{ node_temp }}"
    state: directory
    mode: '0755'

- name: Ensure temporary directory exists on localhost
  delegate_to: localhost
  file:
    path: "{{ storage_temp }}"
    state: directory
    mode: '0755'

- name: Validate configuration before execution
  command: echo "Validating configurations..."
  register: validation_result
  failed_when: "'error' in validation_result.stdout"
